### PR TITLE
[WIP] Chauffeur :heart: Plumber

### PR DESCRIPTION
**Pull request by aaronpowell**
Getting started on Chauffeur integration for Plumber.
- Created a get-all to display groups
- Created an add operation to create a new group. This will need to do a bit more refactoring since it uses the Utility static class that uses UmbracoContext that is null and thus crashes. Need to refactor that class a bit

### CODE REVIEW

**Comment by aaronpowell** [comment]
@nathanwoulfe this is mostly to show you _how_ I'd go about doing Chauffeur for Plumber, it's by no means complete (so don't merge it 😛).

The `add` operation crashes because of the `Utility` class, which will need quite extensive refactoring (and more than I am in a position to do tonight).

If you want to try it out, just pull my branch, compile and then run `Chauffeur.Runner.exe` from your demo site's `bin` folder. Using `help` you'll see `workflow-group` is now listed and you can run `workflow-group get-all` to display all groups!

**Comment by aaronpowell** [comment]
Oh, and I figured you'd prefer if I wrote it in C# not F# as I would've normally done 😉

**Comment by nathanwoulfe** [comment]
That's awesome, love it. 

I've been knocking over other refactoring to add more services, particularly for accessing workflow configuration on nodes and content types. Couple of buggy bits, but getting there. It's all on the master branch (really should start using git-flow)

**Comment by nathanwoulfe** [comment]
And yes, C#!

**Comment by nathanwoulfe** [comment]
I've created a feature branch for Chauffeur integration - can you please change the target branch from master?

Once I hit v1 I think I'll revisit my CI/CD chain and do something similar. At the moment I'm only building on tagged merges, typically minor releases, but would be really useful to have pre-release available on nuget.

**Comment by aaronpowell** [comment]
Feel free to grab the build scripts I use for Chauffeur, and happy to walk you through them too :)

**Comment by aaronpowell** [comment]
PR retargeted

**Pull request merged**
