### PR TITLE
Implementing the rest of the groups controller via a service

### PR DESCRIPTION
**Pull request by aaronpowell**
I hadn't finished the service implementation when you merged yesterday 😛

### CODE REVIEW

**Comment by nathanwoulfe** [comment]
Yeah, sorry, realised that after I'd merged it - wanted to have a look at adding events to the service actions. All good though, CD only runs on tagged merges, so nothing went any further than the master branch.

**Comment by aaronpowell** [comment]
This should cover off all the requirements for the `GroupsController` at least.

**Comment by aaronpowell** [comment]
And the `GroupsController` is really the bulk of what's needing to be refactored for creating a Chauffeur extension on it ;)

**Comment by nathanwoulfe** [comment]
What about managing the actual workflow settings - ie flows on nodes or content types? Would be cool to be able to move those between environments too. Could look at doing some sort of import/export endpoint to produce/consume a JSON object - not sure what works best from the Chauffeur end though.

I'm planning on changing the settings to store JSON so I can add/remove settings without DB schema changes, so could use something similar to export the entire config for approval flows.

**Comment by aaronpowell** [comment]
Yeah defining the structure of the workflow would be good (first goal was the groups 😉).


I'd err on the side of caution about converting everything to JSON to be stored on disk, if you do that you have a bit of a challenge in a distributed environment, as there's no central source of truth (what if I log into Umbraco and change something? How do you replicate those changes across environments? that kind of stuff).

No reason you couldn't use Chauffeur to import/export via JSON using Chauffeur though, just like the XML that it uses already.

**Pull request merged**
