### PR TITLE
Handle Event Cancellations and EventMessages in similar fashion as default Umbraco

### PR DESCRIPTION
**Pull request by tomfulton**
We had a few custom event handlers that could cancel a Publish/UnPublish and/or add `EventMessages` to display to the executing user.  In Plumber, these cancellations were manifesting as YSODs, and `EventMessages` not being shown.  The goal of this PR was to further align the Plumber Publish/UnPublish experience with that of the default Umbraco backoffice, by:

When approving a Publish/UnPublish via Plumber:

1) handle "canceled" events gracefully
2) display any `EventMessages` added in the Publish/UnPublish pipeline as notifications

### Introduce `UmbracoOperationFailedException`

Currently Plumber treats any failed Workflow/Process operation as a `WorkflowException`, which manifests as a 500 and subsequent YSOD in the UI.

The `UmbracoOperationFailedException` was added to distinguish cases where Publish/UnPublish fails but without an exception (e.g. canceled via event).  In this case we'll return a 200 (seems to be the only way to bypass Umbraco's 500 behavior) and display the appropriate cancellation messages as notifications (see below).

All other exceptions, including any returned on the `Attempt<PublishStatus>`, will continue to be treated as a `WorkflowException`, and show the YSOD dialog in the UI based on debug settings.

### Add `EventMessages` to Processes

Umbraco allows adding custom `EventMessages` during the default Publish/UnPublish pipelines, which manifest as notifications in the UI.

To track these, this PR adds a `IEnumerable<EventMessage> EventMessages` property to the `WorkflowProcess`, populated from new methods in `DocumentPublishProcess` and `DocumentUnpublishProcess`, and returns them to the UI.

This also adds some [helpers](https://github.com/nathanwoulfe/Plumber/pull/93/commits/224ae2a2a482b1b68d8680bfc6977fa55f1d52cc#diff-41e637609527ed41b8c93c7218312498) for mimicking the default notifications that Umbraco adds in the `ContentController`.

## Examples
See screenshots of various states with the updated failure handling and notifications.  Prior to this update, any cancellation or exception showed the YSOD dialog.

* note, screenshots assume Admin workflow user, so 'requests' are continuing to actions
* note, screenshots show Publish but behavior is the same for UnPublish

##### Publish Canceled via Event, with EventMessages added

```
private void ContentService_Publishing(Umbraco.Core.Publishing.IPublishingStrategy sender, Umbraco.Core.Events.PublishEventArgs<Umbraco.Core.Models.IContent> e)
{
    e.CancelOperation(new EventMessage("Publish Event canceled due to xyz!", "Test Message", EventMessageType.Warning));
}

```

p1_2

##### Publish Canceled via Event, with no EventMessages added

```
private void ContentService_UnPublishing(Umbraco.Core.Publishing.IPublishingStrategy sender, PublishEventArgs<Umbraco.Core.Models.IContent> e)
{
    e.Cancel = true;
}

```

v2_2

##### Unhandled exception during Publishing or elsewhere

```
private void ContentService_Publishing(Umbraco.Core.Publishing.IPublishingStrategy sender, Umbraco.Core.Events.PublishEventArgs<Umbraco.Core.Models.IContent> e)
{
    throw new Exception();
}
```

ex22

##### Success - with additional EventMessages added via Publishing event

```
private void ContentService_Publishing(Umbraco.Core.Publishing.IPublishingStrategy sender, Umbraco.Core.Events.PublishEventArgs<Umbraco.Core.Models.IContent> e)
{
    e.Messages.Add(new EventMessage("Custom Message Here", "and more detail", EventMessageType.Info));
}
```

v32

##### Success

success

---

### Other notes

Let me know if you have any thoughts, happy to refactor as you see fit!  A couple thoughts so far:

##### Default Notifications
Umbraco's `ContentController` actions have a few cases where notifications are added by default based on the `PublishStatus` -- including the 'Canceled by 3rd party add-in' message.  I was only after the cancelation message, but thought it might (?) make sense to handle all of the conditions that the `ContentController` does, so went ahead and duplicated all of these scenarios in Plumber just in case - see [`NotificationHelpers.GetUmbracoDefaultEventMessages`](https://github.com/nathanwoulfe/Plumber/pull/93/commits/224ae2a2a482b1b68d8680bfc6977fa55f1d52cc#diff-41e637609527ed41b8c93c7218312498R66).

##### Plumber vs Umbraco notifications
With this PR, there will always be 2 notifications when performing a Publish/UnPublish - one from Umbraco and one from Plumber.  I wasn't sure about this, but thought it might be comforting for users unfamiliar with Plumber to also see the standard Umbraco message.  Happy to remove this if you think it might be too much.

##### Storing EventMessages

Currently I am grabbing the `EventMessages` from the `PublishStatus`/`UnPublishStatus` result from the `ContentService` and storing it on a new property of the `WorkflowProcess`.  

There might be some better places to track this, open to ideas.  I also noticed we might be able to use `UmbracoContext.GetCurrentEventMessages()` instead, but ended up keeping them in each `Process` (mostly), to make it easier to support the "default notifications" which are publish/unpublish-specific.

### CODE REVIEW

**Comment by nathanwoulfe** [comment]
Hi @tomfulton, this looks magnificent - I'll need to find a bit of time to go through it and understand what's happening, but on the surface it looks awesome. I might go back and refined the notification formatting for my messages, removing the caps to make em look the same as the Umbraco native ones (might change the type to info too, and leave success ones to umbraco only).

Also awesome to have PR submitted rather than just an issue raised! Much appreciated!

**Comment by tomfulton** [comment]
Sounds great, glad to help!  Happy to take a stab at the messaging updates or anything else if you like.

One thing I've been wondering about while testing this - if the Publish is canceled or throws an exception during approval, the entire Workflow seems to be canceled/completed - in both the new and updated code.  Would it make sense to keep the Workflow open, but note that the approval/publish task failed, so that the approver can potentially fix the issue and re-approve/publish?  Or is it the intention that the Workflow should be completed?  Is it worth considering different behavior for a cancellation vs exception?

**Comment by nathanwoulfe** [comment]
Yeah, it doesn't really make sense to end the process of the publish fails. Better behaviour might be to treat it like an approval rejection and send the content back to the original editor for revision. There's a value on the WorkflowStatus enum for errored, which isn't used - I don't think it would be a huge change to set the process to errored, update the comment with either the exception message or cancellation reason, and send back to the editor. I'll have a look when I'm merging these changes.

**Comment by nathanwoulfe** [comment]
Actually, looking at this now, I think it makes sense to close the workflow for the sake of a more detailed audit history. If I keep it open and flip the status back to success on a subsequent publish attempt, the previous error is lost. 

I'd prefer to keep it as is, and close the workflow on publishing error/cancellation, track that in the workflow history, and alert the editor that the attempt failed and they need to resubmit.

**Comment by nathanwoulfe** [comment]
Building v1.1.4 now, these changes all included. Thanks again, it's an awesome update.

**Pull request merged**
